title: Jack Beck # your name (or website title) here
logo: "/images/headshot_pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an aspiring Data Analytics professional, currently enrolled in an MSBA program at The Leeds School of Business. I aim to use the skills and knowledge I've obtained throughout my education to create meaningful value in my career.
  <br>
  MS Business Analytics Student at The Leeds School of Business
  <br>
  BS Business Administration: Finance Emphasis
  <br><br>
  <a href="https://www.linkedin.com/in/jack-beck-10679b185/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
