title: Jack Beck # your name (or website title) here
logo: "/images/Beck_Jack_Headshot.jpg?raw=true" # your photo (or logo) here # headshot_pic.png?raw=true
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Data Engineering professional, currently employed as Data Engineering Consultant at DAS42. I aim to use the skills and knowledge I've obtained throughout my career and education to create meaningful value at my workplace. 
  <br>
  MS Business Analytics - The Leeds School of Business
  <br>
  BS Business Administration - The Leeds School of Business
  <br><br>
  <a href="https://www.linkedin.com/in/jack-beck-10679b185/">View My LinkedIn Profile</a>
  <br>
  <a href="https://drive.google.com/file/d/1SzstpEoUq8RKOfzA5K4xacXwLcqwaFYE/view?usp=sharing">View My Resume</a>
  <br>
  <a href="https://www.credly.com/users/jack-beck.bcc15a10">View My Certifications on Credly</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
